In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append('../..')

import pandas as pd
import numpy as np

from functools import reduce 
from utils.use_regression import (create_formula, convert_results_to_df, run_regression)

### 1. Import Data

#### HMDA Data that contains all dummy variables

In [3]:
hmda19_df = pd.read_csv('../../data/hmda_lar/cleaned_data/3_hmda2019_regressiondata_210823.csv',
                        dtype = {'app_credit_model': str, 'metro_code': str})

hmda19_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2433071 entries, 0 to 2433070
Data columns (total 63 columns):
 #   Column                        Dtype  
---  ------                        -----  
 0   black                         float64
 1   latino                        float64
 2   asian_cb                      float64
 3   native                        float64
 4   race_na                       float64
 5   no_coapplicant                float64
 6   na_coapplicant                float64
 7   female                        float64
 8   sex_na                        float64
 9   less_than25                   float64
 10  between25_34                  float64
 11  between45_54                  float64
 12  between55_64                  float64
 13  older_than65                  float64
 14  age_na                        float64
 15  income_log                    float64
 16  loan_log                      float64
 17  property_value_ratio          float64
 18  less30yrs_mortgage    

#### Metro Data

In [4]:
metros_df = pd.read_csv('../../data/census_data/county_to_metro_crosswalk/clean/all_counties_210804.csv',
                        dtype = str)

metros_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3225 entries, 0 to 3224
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   fips_state_code   3224 non-null   object
 1   fips_county_code  3224 non-null   object
 2   county_name       3220 non-null   object
 3   state_name        3220 non-null   object
 4   cbsa_code         1916 non-null   object
 5   cbsa_title        1916 non-null   object
 6   csa_code          1256 non-null   object
 7   csa_title         1256 non-null   object
 8   metro_type        3225 non-null   object
 9   metro_code        1916 non-null   object
 10  metro_name        1916 non-null   object
 11  metro_pop         1915 non-null   object
 12  metro_percentile  3225 non-null   object
 13  metro_type_def    3225 non-null   object
dtypes: object(14)
memory usage: 352.9+ KB


### 2. Reshape metro data

#### Data is at the county level, grouping by metros

In [5]:
metros_df2 = pd.DataFrame(metros_df.groupby(by = ['metro_code', 'metro_name', 'metro_type', 'metro_pop'],
                          dropna = False).size()).reset_index().rename(columns = {0: 'count'}).\
                          drop(columns = {'count'})

metros_df2['metro_pop'] = pd.to_numeric(metros_df2['metro_pop'])

### 3. Filter HMDA data
#### Filtering those NA's that are less than one percent of the column. These values break at the metro level

- 0: Yes
- 1: No

In [6]:
hmda19_df['na_coapplicant'].value_counts(dropna = False, normalize = True) * 100

1.0    99.820145
0.0     0.179855
Name: na_coapplicant, dtype: float64

In [7]:
hmda19_df['age_na'].value_counts(dropna = False, normalize = True) * 100

1.0    99.981957
0.0     0.018043
Name: age_na, dtype: float64

In [8]:
hmda19_df['lender_na'].value_counts(dropna = False, normalize = True) * 100

1.0    99.730135
0.0     0.269865
Name: lender_na, dtype: float64

In [9]:
hmda19_df2 = hmda19_df[(hmda19_df['na_coapplicant'] != 0) & (hmda19_df['age_na'] != 0) &\
                       (hmda19_df['lender_na'] != 0)]

#### Filter out Metros with no code

In [10]:
hmda19_df3 = hmda19_df2[(hmda19_df2['metro_code'].notnull())]

print(len(hmda19_df3))

2357940


### 4. Setup independent variables

In [11]:
independent_vars = ['black', 'latino', 'native', 'asian_cb', 'race_na',
                    'female', 'sex_na',
                    'no_coapplicant', 
                    'younger_than_34', 'older_than_55', 
                    'income_log', 
                    'loan_log', 
                    'property_value_ratio', 
                    'not30yr_mortgage', 
                    'equifax', 'experian', 'other_model', 'more_than_one', 'model_na',
                    'dti_manageable', 'dti_unmanageable', 'dti_struggling',
                    'combined_loan_to_value_ratio',
                    'low_lmi', 'moderate_lmi', 'middle_lmi',
                    'credit_union', 'independent',
                    'lar_count',
                    'non_desktop', 'aus_na', 
                    'white_cat2', 'white_cat3', 'white_cat4']

continuous_vars = ['income_log', 'loan_log', 'combined_loan_to_value_ratio', 'lar_count', 'prop_zscore']

### 5. Get variable count for each metro

In [12]:
metros = hmda19_df3['metro_code'].unique()

print('Number of metros: ' + str(len(metros)))

Number of metros: 959


#### Count all the independent variables for each metro

In [13]:
### Excluding continous variables from the counting
independent_vars2 = [var for var in independent_vars if var not in continuous_vars]

metro_var_holder = []

for independent_var in independent_vars2:
    index_values = []
    index_values.extend(('metro_code', independent_var))
    
    metro_var_df = pd.pivot_table(hmda19_df3, index = index_values, columns = ['loan_outcome'], 
                                  values = ['denied'], aggfunc = 'count', fill_value = 0).reset_index()
    
    metro_var_df.columns = metro_var_df.columns.droplevel(0)
    metro_var_df.columns.name = None
    metro_var_df.columns = ['metro_code', 'variable_flag', 'loan', 'denied']
    metro_var_df['variable_name'] = independent_var
    
    metro_var_holder.append(metro_var_df)
    
metro_varcount_df = pd.concat(metro_var_holder)
metro_varcount_df['metro_code'].nunique()

959

#### Add missing records to the variable count dataframe

In [14]:
metro_varcount_df2 = metro_varcount_df[(metro_varcount_df['variable_flag'] == 0)]
missing_rows_list = []

for metro in metros:
    metro_vars_df = metro_varcount_df2[(metro_varcount_df2['metro_code'] == metro)]
    metro_vars = metro_vars_df['variable_name'].unique()
    
    ### including the continous variables
    for reference_var in independent_vars:
        if reference_var not in metro_vars:
            missing_row = pd.DataFrame([[metro, 0, 0, 0, reference_var]], columns = ['metro_code', 
                                               'variable_flag', 'loan', 'denied', 'variable_name'])
            missing_rows_list.append(missing_row)
            
missing_rows_df = pd.concat(missing_rows_list)         
metro_varcount_df3 = metro_varcount_df2.append(missing_rows_df)

#### Find variable total count and percentages

In [16]:
metro_varcount_df3['total_count'] = metro_varcount_df3['loan'] + metro_varcount_df3['denied']

metro_varcount_df3['loan_pct'] = metro_varcount_df3['loan'].div(metro_varcount_df3['total_count']).multiply(100)

metro_varcount_df3['denied_pct'] = metro_varcount_df3['denied'].\
                                   div(metro_varcount_df3['total_count']).multiply(100)

### 6. Run regression for all metros

In [17]:
metro_analysis = []
i = 0

for metro in metros:
    print(str(i) + ': Metro: ' + metro)
    metro_df = hmda19_df3[(hmda19_df3['metro_code'] == metro)]
    metro_apps = len(metro_df)
    
    regression_formula = create_formula(independent_vars)
    model = run_regression(data = metro_df, formula = regression_formula)
    
    try:
        results = model.fit()
        info = results.mle_retvals['converged']
        
        results_df = convert_results_to_df(results)
        results_df.insert(0, 'metro_code', metro)
        results_df.insert(1, 'metro_apps', metro_apps)
        results_df.insert(2, 'psuedo_rsquare', results.prsquared)
        results_df['iteration_flag'] = info
        
    except:
        independent_nan_list = []
        for regression_var in independent_vars:
            results_dict = {'metro_code': metro, 'metro_apps': metro_apps, 'variable_name': regression_var, 
                            'standard_error': np.nan,  'z_value': np.nan, 'p_value': np.nan, 'odds_ratio': np.nan, 
                            'iteration_flag': np.nan, 'psuedo_rsquare': np.nan}
            
            non_results_df = pd.DataFrame([results_dict], columns = results_dict.keys())
            independent_nan_list.append(non_results_df)
            
        results_df = pd.concat(independent_nan_list)
        
    metro_analysis.append(results_df)
    i += 1
    
results_df2 = pd.concat(metro_analysis)

0: Metro: 35084
Optimization terminated successfully.
         Current function value: 0.203528
         Iterations 8
1: Metro: 35614
Optimization terminated successfully.
         Current function value: 0.260659
         Iterations 7
2: Metro: 35154
Optimization terminated successfully.
         Current function value: 0.212554
         Iterations 8
3: Metro: 39100
Optimization terminated successfully.
         Current function value: 0.191431
         Iterations 8
4: Metro: 45940
         Current function value: 0.218257
         Iterations: 35
5: Metro: 20700


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.216407
         Iterations 25
6: Metro: 48424
Optimization terminated successfully.
         Current function value: 0.270169
         Iterations 7
7: Metro: 33124
         Current function value: 0.338133
         Iterations: 35
8: Metro: 37964


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.201493
         Iterations: 35
9: Metro: 12100


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.187555
         Iterations: 35
10: Metro: 35004


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.210568
         Iterations 8
11: Metro: 47894
Optimization terminated successfully.
         Current function value: 0.159598
         Iterations 8
12: Metro: 15804
Optimization terminated successfully.
         Current function value: 0.174943
         Iterations 8
13: Metro: 33874
Optimization terminated successfully.
         Current function value: 0.158975
         Iterations 8
14: Metro: 42540
Optimization terminated successfully.
         Current function value: 0.225927
         Iterations 17
15: Metro: 22744
Optimization terminated successfully.
         Current function value: 0.306555
         Iterations 7
16: Metro: 44300
         Current function value: 0.191518
         Iterations: 35
17: Metro: 36740
Optimization terminated successfully.
         Current function value: 0.236587
         Iterations 7
18: Metro: 10900
Optimization terminated successfully.
         Current function value: 0.197833
   

/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.158466
         Iterations 8
24: Metro: 10580
Optimization terminated successfully.
         Current function value: 0.126827
         Iterations 8
25: Metro: 36140
         Current function value: 0.194130
         Iterations: 35
26: Metro: 14860
Optimization terminated successfully.
         Current function value: 0.210527
         Iterations 7
27: Metro: 15764
Optimization terminated successfully.
         Current function value: 0.147661
         Iterations 8
28: Metro: 45300
Optimization terminated successfully.
         Current function value: 0.228183
         Iterations 7
29: Metro: 29460
         Current function value: 0.253962
         Iterations: 35
30: Metro: 45060


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.165774
         Iterations 8
31: Metro: 37340
         Current function value: 0.229650
         Iterations: 35
32: Metro: 28940


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.172689
         Iterations 22
33: Metro: 42940
         Current function value: 0.230941
         Iterations: 35
34: Metro: 34100
         Current function value: 0.205367
         Iterations: 35
35: Metro: 28700
         Current function value: 0.158466
         Iterations: 35
36: Metro: 35460


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
37: Metro: 27740
         Current function value: 0.164286
         Iterations: 35
38: Metro: 34980
Optimization terminated successfully.
         Current function value: 0.174689
         Iterations 9
39: Metro: 16860
Optimization terminated successfully.
         Current function value: 0.154070
         Iterations 8
40: Metro: 18900
         Current function value: 0.153090
         Iterations: 35
41: Metro: 24620


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
42: Metro: 17420
         Current function value: 0.147641
         Iterations: 35
43: Metro: 48864
Optimization terminated successfully.
         Current function value: 0.167368
         Iterations 8
44: Metro: 20100
Optimization terminated successfully.
         Current function value: 0.160005
         Iterations 30
45: Metro: 41540
Optimization terminated successfully.
         Current function value: 0.168634
         Iterations 8
46: Metro: 33980


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
47: Metro: 20500
Optimization terminated successfully.
         Current function value: 0.157726
         Iterations 9
48: Metro: 49180
         Current function value: 0.181448
         Iterations: 35
49: Metro: 19660


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.233472
         Iterations 8
50: Metro: 16740
Optimization terminated successfully.
         Current function value: 0.178307
         Iterations 8
51: Metro: 27260
Optimization terminated successfully.
         Current function value: 0.214584
         Iterations 7
52: Metro: 14380


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
53: Metro: 24660
Optimization terminated successfully.
         Current function value: 0.169816
         Iterations 8
54: Metro: 39580
Optimization terminated successfully.
         Current function value: 0.148290
         Iterations 9
55: Metro: 43140


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
56: Metro: 34940
Optimization terminated successfully.
         Current function value: 0.269402
         Iterations 7
57: Metro: 37860
Optimization terminated successfully.
         Current function value: 0.193260
         Iterations 8
58: Metro: 19124
Optimization terminated successfully.
         Current function value: 0.178727
         Iterations 8
59: Metro: 41700
Optimization terminated successfully.
         Current function value: 0.218649
         Iterations 7
60: Metro: 15980
         Current function value: 0.238210
         Iterations: 35
61: Metro: 26420


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.215989
         Iterations 7
62: Metro: 12420
Optimization terminated successfully.
         Current function value: 0.186873
         Iterations 8
63: Metro: 18880
         Current function value: 0.189766
         Iterations: 35
64: Metro: 47260
Optimization terminated successfully.
         Current function value: 0.143651
         Iterations 8
65: Metro: 40060
Optimization terminated successfully.
         Current function value: 0.117679
         Iterations 8
66: Metro: 23224
Optimization terminated successfully.
         Current function value: 0.161599
         Iterations 8
67: Metro: 31084
Optimization terminated successfully.
         Current function value: 0.243558
         Iterations 7
68: Metro: 12260


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
69: Metro: 25940
         Current function value: 0.147875
         Iterations: 35
70: Metro: 29404


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.174451
         Iterations 8
71: Metro: 16984
Optimization terminated successfully.
         Current function value: 0.194791
         Iterations 8
72: Metro: 23844
         Current function value: 0.132546
         Iterations: 35
73: Metro: 10300


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.125268
         Iterations: 35
74: Metro: 39540
         Current function value: 0.168422
         Iterations: 35
75: Metro: 20994


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.153573
         Iterations 8
76: Metro: 16580


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
77: Metro: 11460
Optimization terminated successfully.
         Current function value: 0.140932
         Iterations 25
78: Metro: 42644
Optimization terminated successfully.
         Current function value: 0.166433
         Iterations 8
79: Metro: 11244
Optimization terminated successfully.
         Current function value: 0.221287
         Iterations 7
80: Metro: 36084
Optimization terminated successfully.
         Current function value: 0.206251
         Iterations 8
81: Metro: 37100


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/pandas/core/arraylike.py:358: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/d

         Current function value: inf
         Iterations: 35
82: Metro: 40140
Optimization terminated successfully.
         Current function value: 0.236549
         Iterations 7
83: Metro: 12540
Optimization terminated successfully.
         Current function value: 0.163721
         Iterations 8
84: Metro: 41940
         Current function value: 0.215119
         Iterations: 35
85: Metro: 41740


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.214594
         Iterations 8
86: Metro: 40900
Optimization terminated successfully.
         Current function value: 0.181873
         Iterations 8
87: Metro: 46700
Optimization terminated successfully.
         Current function value: 0.186212
         Iterations 8
88: Metro: 12060
Optimization terminated successfully.
         Current function value: 0.217365
         Iterations 8
89: Metro: 45580


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
90: Metro: 31420
         Current function value: 0.143062
         Iterations: 35
91: Metro: 40660


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
92: Metro: 29300
         Current function value: inf
         Iterations: 35
93: Metro: 36100
Optimization terminated successfully.
         Current function value: 0.225997
         Iterations 7
94: Metro: 42340
         Current function value: 0.205710
         Iterations: 35
95: Metro: 27600


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
96: Metro: 12020
         Current function value: 0.153979
         Iterations: 35
97: Metro: 15260


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.181333
         Iterations: 35
98: Metro: 23580


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.158875
         Iterations: 35
99: Metro: 18460


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
100: Metro: 33460
Optimization terminated successfully.
         Current function value: 0.120528
         Iterations 9
101: Metro: 47580
         Current function value: 0.150341
         Iterations: 35
102: Metro: 45740


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
103: Metro: 45540
Optimization terminated successfully.
         Current function value: 0.105951
         Iterations 32
104: Metro: 17140
Optimization terminated successfully.
         Current function value: 0.135815
         Iterations 8
105: Metro: 15660
         Current function value: 0.189594
         Iterations: 35
106: Metro: 38240
         Current function value: 0.173213
         Iterations: 35
107: Metro: 44340


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
108: Metro: 21020
         Current function value: 0.091797
         Iterations: 35
109: Metro: 39340


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.132484
         Iterations: 35
110: Metro: 19740


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.162925
         Iterations 9
111: Metro: 25980


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
112: Metro: 10420
         Current function value: 0.139745
         Iterations: 35
113: Metro: 41620


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.160218
         Iterations 9
114: Metro: 24860
         Current function value: 0.163682
         Iterations: 35
115: Metro: 26140


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.254573
         Iterations 7
116: Metro: 38060
Optimization terminated successfully.
         Current function value: 0.189854
         Iterations 8
117: Metro: 23104
Optimization terminated successfully.
         Current function value: 0.161254
         Iterations 8
118: Metro: 21700
         Current function value: 0.114723
         Iterations: 35
119: Metro: 33660
         Current function value: 0.134767
         Iterations: 35
120: Metro: 36260


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.152564
         Iterations: 35
121: Metro: 33860


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.195095
         Iterations: 35
122: Metro: 38940


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.251661
         Iterations 8
123: Metro: 34820
Optimization terminated successfully.
         Current function value: 0.196833
         Iterations 8
124: Metro: 26620
         Current function value: 0.130124
         Iterations: 35
125: Metro: 42680


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.222260
         Iterations: 35
126: Metro: 23420


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.188308
         Iterations 8
127: Metro: 20780
         Current function value: 0.210114
         Iterations: 35
128: Metro: 13820
Optimization terminated successfully.
         Current function value: 0.146983
         Iterations 8
129: Metro: 21340
Optimization terminated successfully.
         Current function value: 0.199637
         Iterations 8
130: Metro: 17900
Optimization terminated successfully.
         Current function value: 0.162918
         Iterations 8
131: Metro: 17980


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
132: Metro: 20660
         Current function value: inf
         Iterations: 35
133: Metro: 10500
         Current function value: 0.094870
         Iterations: 35
134: Metro: 14260
Optimization terminated successfully.
         Current function value: 0.118264
         Iterations 8
135: Metro: 45104
Optimization terminated successfully.
         Current function value: 0.162891
         Iterations 8
136: Metro: 11700
         Current function value: 0.174459
         Iterations: 35
137: Metro: 43620


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.071461
         Iterations: 35
138: Metro: 28060


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
139: Metro: 41100
         Current function value: 0.163756
         Iterations: 35
140: Metro: 24300
         Current function value: 0.155795
         Iterations: 35
141: Metro: 44460
         Current function value: inf
         Iterations: 35
142: Metro: 24060
         Current function value: 0.185528
         Iterations: 35
143: Metro: 40940
         Current function value: inf
         Iterations: 35
144: Metro: 42220
         Current function value: 0.189543
         Iterations: 35
145: Metro: 34580
Optimization terminated successfully.
         Current function value: 0.145189
         Iterations 8
146: Metro: 39900
Optimization terminated successfully.
         Current function value: 0.154524
         Iterations 8
147: Metro: 36420
Optimization terminated successfully.
         Current function value: 0.150967
         Iterations 9
148: Metro: 28180


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
149: Metro: 44700
Optimization terminated successfully.
         Current function value: 0.242263
         Iterations 8
150: Metro: 23940


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
151: Metro: 14720
         Current function value: 0.166144
         Iterations: 35
152: Metro: 33940
         Current function value: 0.059993
         Iterations: 35
153: Metro: 29820
Optimization terminated successfully.
         Current function value: 0.248456
         Iterations 7
154: Metro: 40340
         Current function value: 0.116417
         Iterations: 35
155: Metro: 15860
         Current function value: 0.182644
         Iterations: 35
156: Metro: 28140
Optimization terminated successfully.
         Current function value: 0.132532
         Iterations 8
157: Metro: 10740
Optimization terminated successfully.
         Current function value: 0.168350
         Iterations 8
158: Metro: 16700
Optimization terminated successfully.
         Current function value: 0.198549
         Iterations 8
159: Metro: 48300
         Current function value: 0.145227
         Iterations: 35
160: Metro: 18780


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
161: Metro: 17820
         Current function value: 0.135602
         Iterations: 35
162: Metro: 46060
Optimization terminated successfully.
         Current function value: 0.163890
         Iterations 8
163: Metro: 14500
         Current function value: 0.137378
         Iterations: 35
164: Metro: 26660


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.084900
         Iterations: 35
165: Metro: 41500
Optimization terminated successfully.
         Current function value: 0.232890
         Iterations 22
166: Metro: 24540
Optimization terminated successfully.
         Current function value: 0.160481
         Iterations 9
167: Metro: 16100


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
168: Metro: 41884
Optimization terminated successfully.
         Current function value: 0.191139
         Iterations 8
169: Metro: 39150
Optimization terminated successfully.
         Current function value: 0.147221
         Iterations 8
170: Metro: 42100


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
171: Metro: 22280
         Current function value: 0.067316
         Iterations: 35
172: Metro: 36500
Optimization terminated successfully.
         Current function value: 0.142449
         Iterations 8
173: Metro: 33260
         Current function value: 0.148702
         Iterations: 35
174: Metro: 33140


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.170337
         Iterations: 35
175: Metro: 39380


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.172229
         Iterations: 35
176: Metro: 46520


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.180367
         Iterations 8
177: Metro: 39420


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
178: Metro: 17020
         Current function value: 0.135460
         Iterations: 35
179: Metro: 33700


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.201660
         Iterations 8
180: Metro: 42200
         Current function value: 0.188182
         Iterations: 35
181: Metro: 25260


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.130104
         Iterations: 35
182: Metro: 41060
Optimization terminated successfully.
         Current function value: 0.097878
         Iterations 9
183: Metro: 33540
         Current function value: 0.106174
         Iterations: 35
184: Metro: 13380
         Current function value: 0.160969
         Iterations: 35
185: Metro: 32900


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.224271
         Iterations 8
186: Metro: 46860


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
187: Metro: 49100
         Current function value: inf
         Iterations: 35
188: Metro: 28100
         Current function value: inf
         Iterations: 35
189: Metro: 39460
Optimization terminated successfully.
         Current function value: 0.221615
         Iterations 8
190: Metro: 39860
         Current function value: 0.121552
         Iterations: 35
191: Metro: 25720
Optimization terminated successfully.
         Current function value: 0.198126
         Iterations 18
192: Metro: 37740
         Current function value: 0.183245
         Iterations: 35
193: Metro: 48900
Optimization terminated successfully.
         Current function value: 0.150632
         Iterations 18
194: Metro: 25540
Optimization terminated successfully.
         Current function value: 0.182515
         Iterations 8
195: Metro: 16260
         Current function value: 0.229352
         Iterations: 35
196: Metro: 43420
         Current function val

/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
207: Metro: 22580
         Current function value: 0.181352
         Iterations: 35
208: Metro: 22820
         Current function value: inf
         Iterations: 35
209: Metro: 12380
         Current function value: 0.115529
         Iterations: 35
210: Metro: 38900
Optimization terminated successfully.
         Current function value: 0.141175
         Iterations 8
211: Metro: 22060


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
212: Metro: 10140
Optimization terminated successfully.
         Current function value: 0.153918
         Iterations 23
213: Metro: 42140
Optimization terminated successfully.
         Current function value: 0.199893
         Iterations 8
214: Metro: 43900
Optimization terminated successfully.
         Current function value: 0.215979
         Iterations 8
215: Metro: 13720


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
216: Metro: 36940
         Current function value: 0.074574
         Iterations: 35
217: Metro: 14580
         Current function value: 0.110178
         Iterations: 35
218: Metro: 43320
         Current function value: 0.144655
         Iterations: 35
219: Metro: 22660
         Current function value: 0.157797
         Iterations: 35
220: Metro: 40420


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.169618
         Iterations 8
221: Metro: 14740
Optimization terminated successfully.
         Current function value: 0.157179
         Iterations 8
222: Metro: 29420
Optimization terminated successfully.
         Current function value: 0.243366
         Iterations 8
223: Metro: 16940


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
224: Metro: 35440
         Current function value: 0.190961
         Iterations: 35
225: Metro: 16180
         Current function value: 0.062871
         Iterations: 35
226: Metro: 41420
Optimization terminated successfully.
         Current function value: 0.162429
         Iterations 8
227: Metro: 45220
         Current function value: 0.211739
         Iterations: 35
228: Metro: 26740


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
229: Metro: 29660
         Current function value: inf
         Iterations: 35
230: Metro: 32700
         Current function value: inf
         Iterations: 35
231: Metro: 42034
         Current function value: inf
         Iterations: 35
232: Metro: 36020
         Current function value: 0.164301
         Iterations: 35
233: Metro: 12220
         Current function value: 0.110495
         Iterations: 35
234: Metro: 23860


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
235: Metro: 43760
         Current function value: 0.182893
         Iterations: 35
236: Metro: 19940
         Current function value: inf
         Iterations: 35
237: Metro: 32000
         Current function value: 0.052965
         Iterations: 35
238: Metro: 42020


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.142248
         Iterations: 35
239: Metro: 24330


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
240: Metro: 49340
Optimization terminated successfully.
         Current function value: 0.166840
         Iterations 8
241: Metro: 22380
         Current function value: 0.161879
         Iterations: 35
242: Metro: 35300
Optimization terminated successfully.
         Current function value: 0.196326
         Iterations 8
243: Metro: 49740
         Current function value: 0.126233
         Iterations: 35
244: Metro: 22840
         Current function value: 0.095172
         Iterations: 35
245: Metro: 33300


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
246: Metro: 35980
         Current function value: 0.172796
         Iterations: 35
247: Metro: 20260


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.179348
         Iterations 8
248: Metro: 19300
         Current function value: 0.152754
         Iterations: 35
249: Metro: 14454


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.163241
         Iterations 8
250: Metro: 13740
         Current function value: 0.129457
         Iterations: 35
251: Metro: 23540
         Current function value: 0.189838
         Iterations: 35
252: Metro: 20420


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.168221
         Iterations: 35
253: Metro: 31700
Optimization terminated successfully.
         Current function value: 0.176418
         Iterations 8
254: Metro: 25860
         Current function value: 0.158539
         Iterations: 35
255: Metro: 27980
         Current function value: 0.168582
         Iterations: 35
256: Metro: 21260
         Current function value: 0.155439
         Iterations: 35
257: Metro: 39300
Optimization terminated successfully.
         Current function value: 0.177895
         Iterations 8
258: Metro: 34180
         Current function value: 0.110249
         Iterations: 35
259: Metro: 24180


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
260: Metro: 13420
         Current function value: 0.176452
         Iterations: 35
261: Metro: 28420
Optimization terminated successfully.
         Current function value: 0.114535
         Iterations 19
262: Metro: 44140


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/pandas/core/arraylike.py:358: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)


Optimization terminated successfully.
         Current function value: 0.180857
         Iterations 8
263: Metro: 13460
         Current function value: 0.151487
         Iterations: 35
264: Metro: 44100


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
265: Metro: 31140
Optimization terminated successfully.
         Current function value: 0.179069
         Iterations 9
266: Metro: 30460
         Current function value: 0.153912
         Iterations: 35
267: Metro: 40080


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
268: Metro: 48580
         Current function value: inf
         Iterations: 35
269: Metro: 14540
         Current function value: inf
         Iterations: 35
270: Metro: 28500
         Current function value: 0.157041
         Iterations: 35
271: Metro: 12680
         Current function value: 0.172121
         Iterations: 35
272: Metro: 40484
Optimization terminated successfully.
         Current function value: 0.174604
         Iterations 8
273: Metro: 23180
         Current function value: 0.150328
         Iterations: 35
274: Metro: 18260
         Current function value: 0.109261
         Iterations: 35
275: Metro: 43220
         Current function value: 0.108030
         Iterations: 35
276: Metro: 10620
         Current function value: 0.145117
         Iterations: 35
277: Metro: 20220


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
278: Metro: 46140
Optimization terminated successfully.
         Current function value: 0.147557
         Iterations 8
279: Metro: 47300
         Current function value: 0.169674
         Iterations: 35
280: Metro: 14820


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.174509
         Iterations: 35
281: Metro: 38860
Optimization terminated successfully.
         Current function value: 0.166653
         Iterations 8
282: Metro: 39820
Optimization terminated successfully.
         Current function value: 0.133986
         Iterations 9
283: Metro: 18300
         Current function value: 0.484288
         Iterations: 35
284: Metro: 49420
         Current function value: 0.126396
         Iterations: 35
285: Metro: 43940


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
286: Metro: 19000
         Current function value: inf
         Iterations: 35
287: Metro: 41180
Optimization terminated successfully.
         Current function value: 0.141477
         Iterations 9
288: Metro: 45860
         Current function value: 0.236073
         Iterations: 35
289: Metro: 11540
Optimization terminated successfully.
         Current function value: 0.104371
         Iterations 9
290: Metro: 36780
         Current function value: 0.125936
         Iterations: 35
291: Metro: 33340
         Current function value: 0.153908
         Iterations: 35
292: Metro: 24580


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.122080
         Iterations: 35
293: Metro: 34900


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
294: Metro: 33740
         Current function value: 0.109515
         Iterations: 35
295: Metro: 16140


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
296: Metro: 47940
         Current function value: 0.085105
         Iterations: 35
297: Metro: 16300


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.088252
         Iterations: 35
298: Metro: 38420


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
299: Metro: 31540
Optimization terminated successfully.
         Current function value: 0.124039
         Iterations 8
300: Metro: 34700
         Current function value: 0.173315
         Iterations: 35
301: Metro: 19780
Optimization terminated successfully.
         Current function value: 0.125224
         Iterations 9
302: Metro: 26980
         Current function value: 0.074192
         Iterations: 35
303: Metro: 29100


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.071118
         Iterations: 35
304: Metro: 13180


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
305: Metro: 43100
Optimization terminated successfully.
         Current function value: 0.152350
         Iterations 28
306: Metro: 12660
         Current function value: 0.186550
         Iterations: 35
307: Metro: 22540
         Current function value: inf
         Iterations: 35
308: Metro: 19340
         Current function value: 0.103502
         Iterations: 35
309: Metro: 32380


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
310: Metro: 17540
         Current function value: inf
         Iterations: 35
311: Metro: 39500
         Current function value: inf
         Iterations: 35
312: Metro: 42860
         Current function value: 0.221419
         Iterations: 35
313: Metro: 27500
Optimization terminated successfully.
         Current function value: 0.149473
         Iterations 9
314: Metro: 11180
         Current function value: inf
         Iterations: 35
315: Metro: 32820
         Current function value: 0.160462
         Iterations: 35
316: Metro: 19180


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.158506
         Iterations: 35
317: Metro: 22700
         Current function value: 0.167294
         Iterations: 35
318: Metro: 15460
         Current function value: 0.236676
         Iterations: 35
319: Metro: 24380
320: Metro: 23300
         Current function value: inf
         Iterations: 35
321: Metro: 18140


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


Optimization terminated successfully.
         Current function value: 0.152664
         Iterations 8
322: Metro: 17460
Optimization terminated successfully.
         Current function value: 0.154279
         Iterations 8
323: Metro: 19430
Optimization terminated successfully.
         Current function value: 0.109696
         Iterations 9
324: Metro: 44220


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
325: Metro: 48540
         Current function value: inf
         Iterations: 35
326: Metro: 17300
         Current function value: 0.211950
         Iterations: 35
327: Metro: 46500


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
328: Metro: 47920
         Current function value: inf
         Iterations: 35
329: Metro: 34540
         Current function value: inf
         Iterations: 35
330: Metro: 45660
         Current function value: 0.178913
         Iterations: 35
331: Metro: 13340
         Current function value: inf
         Iterations: 35
332: Metro: 32020
         Current function value: 0.099519
         Iterations: 35
333: Metro: 11740
         Current function value: 0.101222
         Iterations: 35
334: Metro: 49300
         Current function value: 0.109151
         Iterations: 35
335: Metro: 46100
         Current function value: 0.146770
         Iterations: 35
336: Metro: 15340
         Current function value: inf
         Iterations: 35
337: Metro: 31900
         Current function value: inf
         Iterations: 35
338: Metro: 30620
         Current function value: 0.147008
         Iterations: 35
339: Metro: 11780
         Current funct

/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
346: Metro: 31940
         Current function value: 0.214730
         Iterations: 35
347: Metro: 20740
         Current function value: 0.139768
         Iterations: 35
348: Metro: 27020
         Current function value: inf
         Iterations: 35
349: Metro: 44620
         Current function value: 0.125309
         Iterations: 35
350: Metro: 48140
         Current function value: 0.195406
         Iterations: 35
351: Metro: 14140
         Current function value: inf
         Iterations: 35
352: Metro: 48620
Optimization terminated successfully.
         Current function value: 0.148110
         Iterations 9
353: Metro: 49060


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
354: Metro: 45820
Optimization terminated successfully.
         Current function value: 0.141613
         Iterations 9
355: Metro: 29940
         Current function value: 0.092322
         Iterations: 35
356: Metro: 31740
         Current function value: 0.087679
         Iterations: 35
357: Metro: 41460


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
358: Metro: 36840
         Current function value: inf
         Iterations: 35
359: Metro: 27100
         Current function value: inf
         Iterations: 35
360: Metro: 47380
Optimization terminated successfully.
         Current function value: 0.141690
         Iterations 8
361: Metro: 25420
Optimization terminated successfully.
         Current function value: 0.150015
         Iterations 8
362: Metro: 19804
Optimization terminated successfully.
         Current function value: 0.196307
         Iterations 8
363: Metro: 28660
         Current function value: 0.148832
         Iterations: 35
364: Metro: 36220


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.156471
         Iterations: 35
365: Metro: 14100
         Current function value: 0.122002
         Iterations: 35
366: Metro: 11820


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
367: Metro: 43780
         Current function value: 0.154883
         Iterations: 35
368: Metro: 35380


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.179729
         Iterations: 35
369: Metro: 22500


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.189074
         Iterations 8
370: Metro: 25180
Optimization terminated successfully.
         Current function value: 0.162485
         Iterations 23
371: Metro: 29540
         Current function value: 0.127679
         Iterations: 35
372: Metro: 36540


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.101706
         Iterations 9
373: Metro: 42700
         Current function value: 0.230778
         Iterations: 35
374: Metro: 25060


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.209924
         Iterations 8
375: Metro: 42620


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
376: Metro: 46660
         Current function value: inf
         Iterations: 35
377: Metro: 22180
         Current function value: 0.234932
         Iterations: 35
378: Metro: 31260


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.177467
         Iterations: 35
379: Metro: 29180


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
380: Metro: 26900
Optimization terminated successfully.
         Current function value: 0.148383
         Iterations 8
381: Metro: 17660
         Current function value: 0.129250
         Iterations: 35
382: Metro: 47220
         Current function value: 0.177178
         Iterations: 35
383: Metro: 26220


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.127775
         Iterations: 35
384: Metro: 42980


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
385: Metro: 30380
         Current function value: inf
         Iterations: 35
386: Metro: 41980
         Current function value: 0.366262
         Iterations: 35
387: Metro: 32780
         Current function value: 0.129667
         Iterations: 35
388: Metro: 21660


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.145826
         Iterations 8
389: Metro: 10540
         Current function value: 0.138767
         Iterations: 35
390: Metro: 39260


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
391: Metro: 46300
         Current function value: inf
         Iterations: 35
392: Metro: 18700
         Current function value: inf
         Iterations: 35
393: Metro: 28900
         Current function value: inf
         Iterations: 35
394: Metro: 24420
         Current function value: 0.133374
         Iterations: 35
395: Metro: 45520
         Current function value: inf
         Iterations: 35
396: Metro: 40700
         Current function value: 0.162401
         Iterations: 35
397: Metro: 25840
         Current function value: 0.176948
         Iterations: 35
398: Metro: 29260
         Current function value: inf
         Iterations: 35
399: Metro: 43740
         Current function value: 0.219915
         Iterations: 35
400: Metro: 26500
         Current function value: inf
         Iterations: 35
401: Metro: 27780
         Current function value: inf
         Iterations: 35
402: Metro: 26860
         Current function value:

/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
405: Metro: 29740
         Current function value: inf
         Iterations: 35
406: Metro: 35700
         Current function value: 0.085014
         Iterations: 35
407: Metro: 26020
         Current function value: 0.058476
         Iterations: 35
408: Metro: 40760
         Current function value: inf
         Iterations: 35
409: Metro: 43500
         Current function value: inf
         Iterations: 35
410: Metro: 23820
         Current function value: 0.127113
         Iterations: 35
411: Metro: 40740
         Current function value: 0.207207
         Iterations: 35
412: Metro: 12700
         Current function value: 0.158299
         Iterations: 35
413: Metro: 38340
         Current function value: 0.166150
         Iterations: 35
414: Metro: 30280


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.151165
         Iterations: 35
415: Metro: 18980
         Current function value: 0.175775
         Iterations: 35
416: Metro: 15140


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
417: Metro: 43180
         Current function value: inf
         Iterations: 35
418: Metro: 21460
         Current function value: inf
         Iterations: 35
419: Metro: 29980
         Current function value: inf
         Iterations: 35
420: Metro: 12940
Optimization terminated successfully.
         Current function value: 0.125808
         Iterations 8
421: Metro: 25220
         Current function value: 0.083180
         Iterations: 35
422: Metro: 43340
Optimization terminated successfully.
         Current function value: 0.159954
         Iterations 8
423: Metro: 27340
         Current function value: 0.201094
         Iterations: 35
424: Metro: 24780
         Current function value: 0.151813
         Iterations: 35
425: Metro: 47460


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.186280
         Iterations: 35
426: Metro: 34140
         Current function value: 0.075288
         Iterations: 35
427: Metro: 32580
         Current function value: 0.293554
         Iterations: 35
428: Metro: 11260


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.111663
         Iterations: 35
429: Metro: 26820


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.121834
         Iterations: 35
430: Metro: 46340
Optimization terminated successfully.
         Current function value: 0.186714
         Iterations 8
431: Metro: 31020
         Current function value: 0.165989
         Iterations: 35
432: Metro: 33220


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
433: Metro: 13020
         Current function value: inf
         Iterations: 35
434: Metro: 30100
         Current function value: 0.271609
         Iterations: 35
435: Metro: 30860
         Current function value: 0.109248
         Iterations: 35
436: Metro: 21220
         Current function value: 0.055191
         Iterations: 35
437: Metro: 12740
         Current function value: 0.143958
         Iterations: 35
438: Metro: 11980
         Current function value: 0.204784
         Iterations: 35
439: Metro: 30980
         Current function value: 0.225640
         Iterations: 35
440: Metro: 15180


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.330227
         Iterations: 35
441: Metro: 22140
         Current function value: 0.171743
         Iterations: 35
442: Metro: 27140
Optimization terminated successfully.
         Current function value: 0.153422
         Iterations 8
443: Metro: 41820


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
444: Metro: 18580
         Current function value: 0.212681
         Iterations: 35
445: Metro: 13540


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.084521
         Iterations: 35
446: Metro: 23060
Optimization terminated successfully.
         Current function value: 0.118631
         Iterations 8
447: Metro: 44540


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
448: Metro: 18180
         Current function value: 0.151820
         Iterations: 35
449: Metro: 49020
         Current function value: 0.099868
         Iterations: 35
450: Metro: 43300


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.182786
         Iterations: 35
451: Metro: 15700


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.216845
         Iterations: 35
452: Metro: 22420


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/pandas/core/arraylike.py:358: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/d

         Current function value: inf
         Iterations: 35
453: Metro: 15680
         Current function value: 0.142359
         Iterations: 35
454: Metro: 16820


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.110135
         Iterations: 35
455: Metro: 40860


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
456: Metro: 30340
         Current function value: 0.136005
         Iterations: 35
457: Metro: 34380
         Current function value: inf
         Iterations: 35
458: Metro: 40980
         Current function value: 0.120810
         Iterations: 35
459: Metro: 25740


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.125364
         Iterations: 35
460: Metro: 12140
         Current function value: 0.178738
         Iterations: 35
461: Metro: 33780


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
462: Metro: 24900
         Current function value: inf
         Iterations: 35
463: Metro: 21580
         Current function value: inf
         Iterations: 35
464: Metro: 13140
Optimization terminated successfully.
         Current function value: 0.225058
         Iterations 7
465: Metro: 24340
         Current function value: 0.127479
         Iterations: 35
466: Metro: 24140
         Current function value: 0.167578
         Iterations: 35


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


467: Metro: 16540
         Current function value: 0.129266
         Iterations: 35
468: Metro: 11420
         Current function value: 0.125069
         Iterations: 35
469: Metro: 33420


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
470: Metro: 34300
         Current function value: inf
         Iterations: 35
471: Metro: 12300
         Current function value: 0.144820
         Iterations: 35
472: Metro: 14780
         Current function value: 0.136079
         Iterations: 35
473: Metro: 25460
         Current function value: inf
         Iterations: 35
474: Metro: 13940
         Current function value: 0.119702
         Iterations: 35
475: Metro: 45500
         Current function value: 0.119783
         Iterations: 35
476: Metro: 27620
         Current function value: inf
         Iterations: 35
477: Metro: 27220
         Current function value: 0.204214
         Iterations: 35
478: Metro: 26300
         Current function value: 0.178145
         Iterations: 35
479: Metro: 10940


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
480: Metro: 37060
         Current function value: inf
         Iterations: 35
481: Metro: 25900
         Current function value: 0.227299
         Iterations: 35
482: Metro: 40300


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.185730
         Iterations: 35
483: Metro: 45780
         Current function value: 0.149094
         Iterations: 35
484: Metro: 10980


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
485: Metro: 46620
         Current function value: inf
         Iterations: 35
486: Metro: 17780
Optimization terminated successfully.
         Current function value: 0.153248
         Iterations 8
487: Metro: 36830


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
488: Metro: 19460
         Current function value: 0.166302
         Iterations: 35
489: Metro: 41760


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.203367
         Iterations: 35
490: Metro: 40180


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
491: Metro: 16220
         Current function value: 0.141394
         Iterations: 35
492: Metro: 28340
         Current function value: 0.126969
         Iterations: 35
493: Metro: 21820
         Current function value: 0.077668
         Iterations: 35
494: Metro: 21780
Optimization terminated successfully.
         Current function value: 0.109266
         Iterations 9
495: Metro: 37580


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
496: Metro: 34260
         Current function value: 0.154501
         Iterations: 35
497: Metro: 23460
         Current function value: inf
         Iterations: 35
498: Metro: 45180
         Current function value: 0.124365
         Iterations: 35
499: Metro: 46380


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
500: Metro: 49660
Optimization terminated successfully.
         Current function value: 0.193380
         Iterations 8
501: Metro: 49700
Optimization terminated successfully.
         Current function value: 0.214988
         Iterations 8
502: Metro: 40100


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
503: Metro: 48020
         Current function value: 0.163487
         Iterations: 35
504: Metro: 44500
         Current function value: inf
         Iterations: 35
505: Metro: 27380
         Current function value: 0.316856
         Iterations: 35
506: Metro: 21140
         Current function value: 0.121232
         Iterations: 35
507: Metro: 47660


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
508: Metro: 13660
         Current function value: 0.095996
         Iterations: 35
509: Metro: 24980
         Current function value: inf
         Iterations: 35
510: Metro: 39780
         Current function value: 0.087148
         Iterations: 35
511: Metro: 37260
         Current function value: inf
         Iterations: 35
512: Metro: 40580
         Current function value: 0.187125
         Iterations: 35
513: Metro: 23900
         Current function value: 0.166524
         Iterations: 35
514: Metro: 15420
         Current function value: 0.154011
         Iterations: 35
515: Metro: 27860
         Current function value: 0.153649
         Iterations: 35
516: Metro: 39220


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
517: Metro: 38540
         Current function value: 0.080092
         Iterations: 35
518: Metro: 44180
Optimization terminated successfully.
         Current function value: 0.148459
         Iterations 8
519: Metro: 21740
         Current function value: inf
         Iterations: 35
520: Metro: 35220
         Current function value: inf
         Iterations: 35
521: Metro: 28020
         Current function value: 0.096448
         Iterations: 35
522: Metro: 25200


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.207533
         Iterations: 35
523: Metro: 17340
         Current function value: 0.199570
         Iterations: 35
524: Metro: 37900
         Current function value: 0.139491
         Iterations: 35
525: Metro: 29200


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.115984
         Iterations: 35
526: Metro: 22100


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.310684
         Iterations: 35
527: Metro: 14010
Optimization terminated successfully.
         Current function value: 0.106096
         Iterations 23
528: Metro: 19500
         Current function value: 0.133483
         Iterations: 35
529: Metro: 30660


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
530: Metro: 36837
         Current function value: inf
         Iterations: 35
531: Metro: 30780
Optimization terminated successfully.
         Current function value: 0.140584
         Iterations 8
532: Metro: 44420
         Current function value: 0.171800
         Iterations: 35
533: Metro: 18020


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
534: Metro: 45380
         Current function value: inf
         Iterations: 35
535: Metro: 16060
         Current function value: inf
         Iterations: 35
536: Metro: 17860
         Current function value: 0.093097
         Iterations: 35
537: Metro: 27900
         Current function value: inf
         Iterations: 35
538: Metro: 31380
         Current function value: inf
         Iterations: 35
539: Metro: 40220
         Current function value: 0.124453
         Iterations: 35
540: Metro: 47020


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.141247
         Iterations: 35
541: Metro: 27300


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.131815
         Iterations: 35
542: Metro: 10660


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
543: Metro: 37140
         Current function value: 0.126580
         Iterations: 35
544: Metro: 13220
         Current function value: 0.199941
         Iterations: 35
545: Metro: 12900
         Current function value: 0.510595
         Iterations: 35
546: Metro: 40780
         Current function value: inf
         Iterations: 35
547: Metro: 23660
         Current function value: inf
         Iterations: 35
548: Metro: 40380
         Current function value: 0.108517
         Iterations: 35
549: Metro: 37460


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.219358
         Iterations: 35
550: Metro: 22220


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


Optimization terminated successfully.
         Current function value: 0.159358
         Iterations 8
551: Metro: 25300


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
552: Metro: 44580
         Current function value: inf
         Iterations: 35
553: Metro: 46220
         Current function value: 0.158076
         Iterations: 35
554: Metro: 34420


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
555: Metro: 22020
         Current function value: 13.570102
         Iterations: 35
556: Metro: 31220
         Current function value: inf
         Iterations: 35
557: Metro: 37540
         Current function value: inf
         Iterations: 35
558: Metro: 28820
         Current function value: inf
         Iterations: 35
559: Metro: 47820
         Current function value: inf
         Iterations: 35
560: Metro: 28620
         Current function value: 0.200279
         Iterations: 35
561: Metro: 35100
Optimization terminated successfully.
         Current function value: 0.191656
         Iterations 24
562: Metro: 34740
         Current function value: 0.122831
         Iterations: 35
563: Metro: 31300


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
564: Metro: 11100
         Current function value: inf
         Iterations: 35
565: Metro: 10860
         Current function value: inf
         Iterations: 35
566: Metro: 20300
         Current function value: inf
         Iterations: 35
567: Metro: 20900
         Current function value: inf
         Iterations: 35
568: Metro: 48660
         Current function value: 0.092732
         Iterations: 35
569: Metro: 24940


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.078375
         Iterations: 35
570: Metro: 35140


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.216347
         Iterations: 35
571: Metro: 14300
         Current function value: inf
         Iterations: 35


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


572: Metro: 27180
         Current function value: 0.154264
         Iterations: 35
573: Metro: 46900


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
574: Metro: 31180
         Current function value: inf
         Iterations: 35
575: Metro: 40530
         Current function value: inf
         Iterations: 35
576: Metro: 34860
         Current function value: 0.186827
         Iterations: 35
577: Metro: 30020
         Current function value: 0.088434
         Iterations: 35


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


578: Metro: 23240
         Current function value: 0.188193
         Iterations: 35
579: Metro: 20140


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
580: Metro: 38500
         Current function value: 0.136485
         Iterations: 35
581: Metro: 19540
         Current function value: 0.178546
         Iterations: 35
582: Metro: 30700
         Current function value: inf
         Iterations: 35
583: Metro: 31860
         Current function value: 0.150205
         Iterations: 35
584: Metro: 32860
         Current function value: inf
         Iterations: 35
585: Metro: 16460
         Current function value: inf
         Iterations: 35
586: Metro: 44020
         Current function value: inf
         Iterations: 35
587: Metro: 49220
         Current function value: inf
         Iterations: 35
588: Metro: 49460
         Current function value: inf
         Iterations: 35
589: Metro: 44740
         Current function value: inf
         Iterations: 35
590: Metro: 18820
         Current function value: 0.060688
         Iterations: 35
591: Metro: 43980
         Current function value:

/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
603: Metro: 38260
         Current function value: 0.101089
         Iterations: 35
604: Metro: 31930
         Current function value: 0.087561
         Iterations: 35
605: Metro: 14700
         Current function value: inf
         Iterations: 35
606: Metro: 27940
         Current function value: inf
         Iterations: 35
607: Metro: 21060
         Current function value: inf
         Iterations: 35
608: Metro: 47420
         Current function value: inf
         Iterations: 35
609: Metro: 10820
         Current function value: 0.084001
         Iterations: 35
610: Metro: 48820
         Current function value: inf
         Iterations: 35
611: Metro: 22260
         Current function value: 0.140940
         Iterations: 35
612: Metro: 45000
         Current function value: inf
         Iterations: 35
613: Metro: 41660
         Current function value: 0.142616
         Iterations: 35


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


614: Metro: 13300
         Current function value: inf
         Iterations: 35
615: Metro: 10180
         Current function value: 0.112202
         Iterations: 35
616: Metro: 14420
         Current function value: inf
         Iterations: 35
617: Metro: 18620
         Current function value: inf
         Iterations: 35
618: Metro: 46020
         Current function value: 0.186926
         Iterations: 35
619: Metro: 24460
         Current function value: inf
         Iterations: 35
620: Metro: 24260
Optimization terminated successfully.
         Current function value: 0.102010
         Iterations 34
621: Metro: 43580
         Current function value: 0.150845
         Iterations: 35
622: Metro: 46820


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


623: Metro: 35740
         Current function value: inf
         Iterations: 35
624: Metro: 42740


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: 0.125538
         Iterations: 35
625: Metro: 32140
         Current function value: inf
         Iterations: 35
626: Metro: 43260
         Current function value: inf
         Iterations: 35
627: Metro: 13100
         Current function value: inf
         Iterations: 35
628: Metro: 36900
         Current function value: inf
         Iterations: 35
629: Metro: 48780
         Current function value: inf
         Iterations: 35
630: Metro: 35820
         Current function value: inf
         Iterations: 35
631: Metro: 23340
         Current function value: inf
         Iterations: 35
632: Metro: 21420
         Current function value: inf
         Iterations: 35
633: Metro: 10220
         Current function value: inf
         Iterations: 35
634: Metro: 23780
         Current function value: inf
         Iterations: 35
635: Metro: 32340
         Current function value: inf
         Iterations: 35
636: Metro: 18100
         Current function value: inf
         I

/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
680: Metro: 41220
         Current function value: inf
         Iterations: 35
681: Metro: 43700
         Current function value: inf
         Iterations: 35
682: Metro: 19140
         Current function value: inf
         Iterations: 35
683: Metro: 46180
         Current function value: 0.155176
         Iterations: 35
684: Metro: 13980
         Current function value: 0.107496
         Iterations: 35
685: Metro: 30940
         Current function value: inf
         Iterations: 35
686: Metro: 42460
         Current function value: inf
         Iterations: 35
687: Metro: 44900
         Current function value: inf
         Iterations: 35
688: Metro: 12460
         Current function value: inf
         Iterations: 35
689: Metro: 35260
         Current function value: inf
         Iterations: 35
690: Metro: 10700
         Current function value: inf
         Iterations: 35
691: Metro: 45460
         Current function value: 0.206880


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
694: Metro: 11500
         Current function value: 0.142290
         Iterations: 35
695: Metro: 39700


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


696: Metro: 46980
         Current function value: inf
         Iterations: 35
697: Metro: 45980


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
698: Metro: 16420
         Current function value: inf
         Iterations: 35
699: Metro: 29340
         Current function value: 0.155976
         Iterations: 35
700: Metro: 25620


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.124932
         Iterations: 35
701: Metro: 29020
         Current function value: 0.139106
         Iterations: 35
702: Metro: 36300


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
703: Metro: 15500
         Current function value: 0.143667
         Iterations: 35
704: Metro: 44780
         Current function value: inf
         Iterations: 35
705: Metro: 15380
Optimization terminated successfully.
         Current function value: 0.142495
         Iterations 8
706: Metro: 34660


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
707: Metro: 48060
         Current function value: 0.114738
         Iterations: 35
708: Metro: 16340
         Current function value: inf
         Iterations: 35
709: Metro: 18380
         Current function value: inf
         Iterations: 35
710: Metro: 42420
         Current function value: inf
         Iterations: 35
711: Metro: 15100
         Current function value: 0.053508
         Iterations: 35
712: Metro: 38780
         Current function value: inf
         Iterations: 35
713: Metro: 36340
         Current function value: 0.237313
         Iterations: 35
714: Metro: 31340
         Current function value: 0.152534
         Iterations: 35
715: Metro: 45700


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
716: Metro: 35420
         Current function value: 0.204711
         Iterations: 35
717: Metro: 20540
         Current function value: inf
         Iterations: 35
718: Metro: 49080
         Current function value: inf
         Iterations: 35
719: Metro: 32100
         Current function value: 0.120739
         Iterations: 35
720: Metro: 24500
         Current function value: 0.178775
         Iterations: 35
721: Metro: 37620
         Current function value: inf
         Iterations: 35
722: Metro: 28740
         Current function value: 0.209044
         Iterations: 35
723: Metro: 12120


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
724: Metro: 21500
         Current function value: 0.163173
         Iterations: 35
725: Metro: 20980


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
726: Metro: 38220
         Current function value: inf
         Iterations: 35
727: Metro: 31680
         Current function value: inf
         Iterations: 35
728: Metro: 40820
         Current function value: inf
         Iterations: 35
729: Metro: 25760
730: Metro: 37500
         Current function value: 0.136028
         Iterations: 35
731: Metro: 14180
         Current function value: inf
         Iterations: 35
732: Metro: 22620
733: Metro: 18860
         Current function value: inf
         Iterations: 35
734: Metro: 38700
         Current function value: inf
         Iterations: 35
735: Metro: 47700
         Current function value: 0.127910
         Iterations: 35
736: Metro: 19260
         Current function value: 0.125286
         Iterations: 35
737: Metro: 11380
         Current function value: inf
         Iterations: 35
738: Metro: 38620
         Current function value: 0.110032
         Iterations: 35
739: Metro: 19

/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
747: Metro: 22900
Optimization terminated successfully.
         Current function value: 0.143729
         Iterations 8
748: Metro: 15020
         Current function value: inf
         Iterations: 35
749: Metro: 27660
         Current function value: inf
         Iterations: 35
750: Metro: 29380
         Current function value: 0.177107
         Iterations: 35
751: Metro: 37120


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
752: Metro: 40460
         Current function value: inf
         Iterations: 35
753: Metro: 38820
         Current function value: 0.122943
         Iterations: 35
754: Metro: 37660
         Current function value: inf
         Iterations: 35
755: Metro: 15580
         Current function value: 0.130032
         Iterations: 35
756: Metro: 36580
         Current function value: inf
         Iterations: 35
757: Metro: 11220
         Current function value: inf
         Iterations: 35
758: Metro: 13780
         Current function value: 0.164578
         Iterations: 35
759: Metro: 18660
         Current function value: 0.109653
         Iterations: 35
760: Metro: 33180
         Current function value: inf
         Iterations: 35
761: Metro: 16380
         Current function value: inf
         Iterations: 35
762: Metro: 30900
         Current function value: inf
         Iterations: 35
763: Metro: 41400
         Current function value:

/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


         Current function value: 0.152514
         Iterations: 35
771: Metro: 38460
         Current function value: 0.110488
         Iterations: 35
772: Metro: 23380


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
773: Metro: 47620
         Current function value: 0.264953
         Iterations: 35
774: Metro: 24100
         Current function value: 0.237986
         Iterations: 35
775: Metro: 26460
         Current function value: 8.431745
         Iterations: 35
776: Metro: 41780
         Current function value: inf
         Iterations: 35
777: Metro: 35940
         Current function value: 0.062721
         Iterations: 35
778: Metro: 21300
         Current function value: 0.202325
         Iterations: 35
779: Metro: 12180
         Current function value: 0.139360
         Iterations: 35
780: Metro: 24020
         Current function value: 0.097460
         Iterations: 35
781: Metro: 28580
         Current function value: 0.260250
         Iterations: 35
782: Metro: 30140
         Current function value: 0.140347
         Iterations: 35
783: Metro: 22300
         Current function value: 0.052512
         Iterations: 35


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


784: Metro: 27060
         Current function value: 0.048749
         Iterations: 35
785: Metro: 34620


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
786: Metro: 36460
         Current function value: 0.215773
         Iterations: 35
787: Metro: 31660
         Current function value: 0.099614
         Iterations: 35
788: Metro: 42380
         Current function value: 0.145284
         Iterations: 35
789: Metro: 39020
         Current function value: 0.114231
         Iterations: 35
790: Metro: 25880
         Current function value: inf
         Iterations: 35
791: Metro: 35860
         Current function value: inf
         Iterations: 35
792: Metro: 35660
         Current function value: 0.139246
         Iterations: 35
793: Metro: 39980


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
794: Metro: 32940
         Current function value: inf
         Iterations: 35
795: Metro: 30220
         Current function value: inf
         Iterations: 35
796: Metro: 26380
         Current function value: 0.139499
         Iterations: 35
797: Metro: 14020
         Current function value: 0.145064
         Iterations: 35
798: Metro: 15060
         Current function value: inf
         Iterations: 35
799: Metro: 43460
         Current function value: inf
         Iterations: 35
800: Metro: 38100
         Current function value: 0.183279
         Iterations: 35
801: Metro: 44860
         Current function value: inf
         Iterations: 35
802: Metro: 28860
         Current function value: inf
         Iterations: 35
803: Metro: 30060
         Current function value: 0.083020
         Iterations: 35
804: Metro: 21840
         Current function value: inf
         Iterations: 35
805: Metro: 33380
         Current function value:

/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


811: Metro: 26940
         Current function value: inf
         Iterations: 35
812: Metro: 13620


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
813: Metro: 37420
         Current function value: inf
         Iterations: 35
814: Metro: 33020
         Current function value: inf
         Iterations: 35
815: Metro: 22780
         Current function value: inf
         Iterations: 35
816: Metro: 33620
         Current function value: inf
         Iterations: 35
817: Metro: 38740
         Current function value: inf
         Iterations: 35
818: Metro: 32300
         Current function value: inf
         Iterations: 35
819: Metro: 32740
         Current function value: 0.193094
         Iterations: 35
820: Metro: 41260
         Current function value: 0.278895
         Iterations: 35
821: Metro: 46420
         Current function value: inf
         Iterations: 35
822: Metro: 25500
Optimization terminated successfully.
         Current function value: 0.121076
         Iterations 28
823: Metro: 10460
         Current function value: inf
         Iterations: 35
824: Metro: 13700


         Current function value: inf
         Iterations: 35
877: Metro: 35060
         Current function value: inf
         Iterations: 35
878: Metro: 30260
         Current function value: inf
         Iterations: 35
879: Metro: 20580
         Current function value: inf
         Iterations: 35
880: Metro: 45140
         Current function value: inf
         Iterations: 35
881: Metro: 20820
         Current function value: inf
         Iterations: 35
882: Metro: 31500
         Current function value: inf
         Iterations: 35
883: Metro: 27540
         Current function value: 0.122100
         Iterations: 35
884: Metro: 37780
885: Metro: 48220
         Current function value: inf
         Iterations: 35
886: Metro: 44940
         Current function value: 0.151460
         Iterations: 35


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


887: Metro: 25780
         Current function value: 0.209819
         Iterations: 35
888: Metro: 11660


/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/emmanuel/.pyenv/versions/3.8.0/envs/redlining/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35
889: Metro: 32180
         Current function value: inf
         Iterations: 35
890: Metro: 35900
         Current function value: inf
         Iterations: 35
891: Metro: 40260
         Current function value: 0.134813
         Iterations: 35
892: Metro: 15620
         Current function value: inf
         Iterations: 35
893: Metro: 39060
         Current function value: 0.190528
         Iterations: 35
894: Metro: 44980
         Current function value: inf
         Iterations: 35
895: Metro: 36700
         Current function value: 0.184804
         Iterations: 35
896: Metro: 33060
         Current function value: inf
         Iterations: 35
897: Metro: 34780
         Current function value: inf
         Iterations: 35
898: Metro: 11060
         Current function value: inf
         Iterations: 35
899: Metro: 34460
         Current function value: inf
         Iterations: 35
900: Metro: 28380
         Current function value: 0.00

954: Metro: 21860
         Current function value: 0.237304
         Iterations: 35
955: Metro: 48100
         Current function value: inf
         Iterations: 35
956: Metro: 13500
         Current function value: inf
         Iterations: 35
957: Metro: 17640
958: Metro: 27580


### 7. Join results with metros data
#### Is every variable accounted for:
- If a variables has less than 959, then it's missing in certain metros

In [18]:
var_used_check = pd.DataFrame(results_df2['variable_name'].value_counts(dropna = False)).reset_index()

var_used_check[(var_used_check['variable_name'] < 959)]

index  variable_name
34  Intercept            250

#### Join with metro names and var count dataframes

In [19]:
results_df3 = pd.merge(results_df2, metros_df2, how = 'left', on = ['metro_code'])
results_df4 = pd.merge(results_df3, metro_varcount_df3, how = 'left',  on = ['metro_code', 'variable_name'])

### 8. Categorize Results

#### Filter for metros that don't produce any results
- Results Flag 1: No meaningful results, all columns shows up as NaN

In [20]:
results_df4.loc[((results_df4['psuedo_rsquare'].isnull()) & (results_df4['coefficient'].isnull()) & \
                 (results_df4['standard_error'] .isnull()) & (results_df4['z_value'].isnull()) & \
                 (results_df4['p_value'].isnull()) & (results_df4['odds_ratio'].isnull())), 
                 'results_flag'] = '1'

metros_no_results = results_df4[(results_df4['results_flag'] == '1')]['metro_code'].nunique()

all_metros = results_df4['metro_code'].nunique()

#### Metro Results Breakdown:
- 709 metros don't produce results
- 250 metros prodocues results

In [21]:
print('Percent of metros with no results: ' + str(((metros_no_results/all_metros) * 100)))

print('Number of metros that DON\'T produce results: ' + str(metros_no_results))

print('Number of metros that produce results: ' + str(results_df4[(results_df4['results_flag'] != '1')] \
                                                      ['metro_code'].nunique()))

Percent of metros with no results: 73.93117831074035
Number of metros that DON'T produce results: 709
Number of metros that produce results: 250


In [22]:
metros_size_df = pd.DataFrame(results_df4[(results_df4['results_flag'] == '1')].\
                 groupby(by = ['metro_code', 'metro_apps']).size()).reset_index().rename(columns = {0: 'count'})

metros_size_df['metro_apps'].describe()

count     709.000000
mean      473.320169
std       690.641226
min         1.000000
25%       120.000000
50%       235.000000
75%       502.000000
max      7148.000000
Name: metro_apps, dtype: float64

#### Filter for metros that produce the results, but the equation needs work
- Results Flag: 2, no meaningful results because of the equation 

In [23]:
results_df4.loc[(results_df4['psuedo_rsquare'] < .1) | (results_df4['iteration_flag'] == False),
                'results_flag'] = '2'

broken_results_metros = results_df4[(results_df4['results_flag'] == '2')]['metro_code'].nunique()

#### Metro Results Breakdown:
- 121 metros with unreliable results, not enoght variance in variables. 

In [24]:
print('Number of metros with broken results: ' + str(broken_results_metros))
print('Percentage of metros with no results: ' + str((broken_results_metros/all_metros) * 100))

Number of metros with broken results: 122
Percentage of metros with no results: 12.721584984358708


#### Filter for metros where the equation is valid
- Results flag 3: valid results

In [25]:
results_df4.loc[(results_df4['psuedo_rsquare'] >= .1) & (results_df4['iteration_flag'] == True), 
                'results_flag'] = '3'

valid_results_metros = results_df4[(results_df4['results_flag'] == '3')]['metro_code'].nunique()

#### Metro Results Breakdown:
- 128 metros with reliable results.

In [26]:
print('Number of metros with valid results: ' + str(valid_results_metros))
print('Percentage of metros with valid results: ' + str((valid_results_metros/all_metros) * 100))

Number of metros with valid results: 128
Percentage of metros with valid results: 13.347236704900938


#### Overall metros breakdown
- 1: No Results
- 2: Variable Issues
- 3: Results

In [27]:
metro_results_df = pd.DataFrame(results_df4.groupby(by = ['results_flag', 'metro_code']).size()).reset_index().\
                   rename(columns = {0: 'count'})

metro_results_df['results_flag'].value_counts(dropna = False)

1    709
3    128
2    122
Name: results_flag, dtype: int64

### 9. Assessing the variables of valid metros
#### Variables where the p-value and z-value are missing
- 63 records

In [28]:
results_df4.loc[(results_df4['results_flag'] == '3') & (results_df4['z_value'].isnull()) &\
                (results_df4['p_value'].isnull()), 'variable_check'] = '1'

results_df4['variable_check'].value_counts(dropna = False)

NaN    32793
1         63
Name: variable_check, dtype: int64

#### Metros with a varibale that has a missing p-value
- 17 metros that are valid but there's missing p-values in them

In [29]:
missing_pvalues_metros_df = results_df4[(results_df4['results_flag'] == '3') & \
                                        (results_df4['variable_check'] == '1')]

print(missing_pvalues_metros_df['metro_code'].nunique())
missing_pvalues_metros_df['metro_name'].value_counts(dropna = False)

17


Lansing-East Lansing, MI                         12
Rockingham County-Strafford County, NH            6
Yuba City, CA                                     6
Mount Vernon-Anacortes, WA                        6
Madison, WI                                       4
Boise City, ID                                    4
Kennewick-Richland, WA                            4
Evansville, IN-KY                                 3
El Paso, TX                                       3
Knoxville, TN                                     2
Portland-Vancouver-Hillsboro, OR-WA               2
Duluth, MN-WI                                     2
Ocala, FL                                         2
Wilmington, NC                                    2
Reading, PA                                       2
Myrtle Beach-Conway-North Myrtle Beach, SC-NC     2
Ann Arbor, MI                                     1
Name: metro_name, dtype: int64

#### Variables that are not statistcially significant
- 2693 records

In [30]:
results_df4.loc[(results_df4['results_flag'] == '3') & (results_df4['p_value'] >= .05),
                'variable_check'] = '2'

results_df4['variable_check'].value_counts(dropna = False)

NaN    30100
2       2693
1         63
Name: variable_check, dtype: int64

#### Filter for variables that are statistcially significant but need more applications
- Variable Check 3: 448 records

In [31]:
results_df4.loc[(results_df4['results_flag'] == '3') & (results_df4['p_value'] < .05) &\
                (results_df4['total_count'] < 75), 'variable_check'] = '3'

results_df4['variable_check'].value_counts(dropna = False)

NaN    29652
2       2693
3        448
1         63
Name: variable_check, dtype: int64

#### Filter those records that are statistcially signicant but no disparity
- Variable Check 4: 503 records

In [32]:
results_df4.loc[(results_df4['results_flag'] == '3') & (results_df4['p_value'] < .05) &\
                (results_df4['total_count'] >= 75) & (results_df4['odds_ratio'] < 1.45), 
                'variable_check'] = '4'

results_df4['variable_check'].value_counts(dropna = False)

NaN    29149
2       2693
4        503
3        448
1         63
Name: variable_check, dtype: int64

#### Filter those records that are statistcially signicant with a disparity
- Variable Check 5: 677 records

In [33]:
results_df4.loc[(results_df4['results_flag'] == '3') & (results_df4['p_value'] < .05) &\
                (results_df4['total_count'] >= 75) & (results_df4['odds_ratio'] >= 1.45), 
                'variable_check'] = '5'

results_df4['variable_check'].value_counts(dropna = False)

NaN    28472
2       2693
5        677
4        503
3        448
1         63
Name: variable_check, dtype: int64

### 10.  Breakdown of statistcially valid metros for race and ethnicity
- 96 NaN are all Intercept variables

In [34]:
results_df4[(results_df4['results_flag'] == '3')]['variable_check'].value_counts(dropna = False)

2      2693
5       677
4       503
3       448
NaN      96
1        63
Name: variable_check, dtype: int64

#### Statistically Valid Metros Race and Ethnicity Breakdown:
- 2: Not statistically significant -- 295 records
- 5: Statistically significant disparity -- 166 records
- 3: Not enough applications -- 25 records
- 4: Small disparities –– 23 records
- 1: Missing p-values -- 3 records

In [35]:
races = ['black', 'latino', 'asian_cb', 'native']

results_df5 = results_df4[(results_df4['results_flag'] == '3') & (results_df4['variable_name'].isin(races))]

results_df5['variable_check'].value_counts(dropna = False)

2    295
5    166
3     25
4     23
1      3
Name: variable_check, dtype: int64

In [36]:
results_df5['metro_code'].nunique()

128

#### Breakdown of 128 Metros

In [37]:
metro_results = pd.DataFrame(results_df5.groupby(by = ['metro_code', 'variable_check']).size()).reset_index().\
                rename(columns = {0: 'count'})

#### Number of metros with no reliable results:

In [38]:
reliable_metros_df = metro_results[(metro_results['variable_check'] == '5') |\
                                   (metro_results['variable_check'] == '4')]

reliable_metros = reliable_metros_df['metro_code'].unique()

#### Number of metros where all racial and ethnic variables are not statistically significant
- 21 metros

In [39]:
print(metro_results[~(metro_results['metro_code'].isin(reliable_metros)) & \
                     (metro_results['count'] == 4)]['metro_code'].nunique())

metro_results[~(metro_results['metro_code'].isin(reliable_metros)) & \
               (metro_results['count'] == 4)]['variable_check'].unique()

21


array(['2'], dtype=object)

#### Number of metros where all racial and ethnic variables are not reliable
- 16 metros
- Because not statistically significant, not enough applications, or missing a p-value

In [40]:
print(metro_results[~(metro_results['metro_code'].isin(reliable_metros)) & \
                     (metro_results['count'] < 4)]['metro_code'].nunique())

metro_results[~(metro_results['metro_code'].isin(reliable_metros)) & \
               (metro_results['count'] < 4)]['variable_check'].unique()

16


array(['2', '3', '1'], dtype=object)

#### Number of metros with valid results
- 91 metros

In [41]:
valid_results_df = metro_results[(metro_results['variable_check'] == '5') |\
                              (metro_results['variable_check'] == '4')]

valid_results_df['metro_code'].nunique()

91

#### Metros with at least one disparity:
- 89 metros

In [42]:
valid_results_df[(valid_results_df['variable_check'] == '5')]['metro_code'].nunique()

89

#### Metros where the only valid result is a small disparity
- 2 metros

In [43]:
disparity_metro = valid_results_df[(valid_results_df['variable_check'] == '5')]['metro_code'].unique()

valid_results_df[~(valid_results_df['metro_code'].isin(disparity_metro))]['metro_code'].nunique()

2

### 11. Places with small disparities

In [44]:
print(results_df5[(results_df5['variable_check'] == '4')]['metro_name'].nunique())

results_df5[(results_df5['variable_check'] == '4')]['metro_name'].value_counts(dropna = False)

18


New York-Jersey City-White Plains, NY-NJ     2
Phoenix-Mesa-Chandler, AZ                    2
Houston-The Woodlands-Sugar Land, TX         2
Orlando-Kissimmee-Sanford, FL                2
Las Vegas-Henderson-Paradise, NV             2
San Diego-Chula Vista-Carlsbad, CA           1
Seattle-Bellevue-Kent, WA                    1
Tampa-St. Petersburg-Clearwater, FL          1
Austin-Round Rock-Georgetown, TX             1
Nassau County-Suffolk County, NY             1
Newark, NJ-PA                                1
Chicago-Naperville-Evanston, IL              1
Kansas City, MO-KS                           1
Fort Lauderdale-Pompano Beach-Sunrise, FL    1
Los Angeles-Long Beach-Glendale, CA          1
Portland-Vancouver-Hillsboro, OR-WA          1
New Brunswick-Lakewood, NJ                   1
Charlotte-Concord-Gastonia, NC-SC            1
Name: metro_name, dtype: int64

#### Places where the only reliable results are small disparities

In [45]:
small_disparities = valid_results_df[~(valid_results_df['metro_code'].isin(disparity_metro))]['metro_code']

results_df5[(results_df5['metro_code'].isin(small_disparities)) & (results_df5['variable_check'] == '4')]\
[['metro_name', 'variable_name', 'p_value', 'odds_ratio', 'variable_check']]

metro_name variable_name   p_value  \
524   Fort Lauderdale-Pompano Beach-Sunrise, FL         black  0.000018   
5306           Las Vegas-Henderson-Paradise, NV         black  0.002907   
5309           Las Vegas-Henderson-Paradise, NV      asian_cb  0.019246   

      odds_ratio variable_check  
524     1.433741              4  
5306    1.415229              4  
5309    1.217433              4

#### Smallest disparities overall

In [46]:
results_df5[(results_df5['variable_check'] == '4')][['metro_name', 'variable_name', 'p_value', 'odds_ratio', 
                                                     'variable_check']].sort_values(by = ['odds_ratio']).head(5)

metro_name variable_name   p_value  \
2329       Los Angeles-Long Beach-Glendale, CA        latino  0.016634   
39    New York-Jersey City-White Plains, NY-NJ      asian_cb  0.000722   
353           Nassau County-Suffolk County, NY      asian_cb  0.047683   
5309          Las Vegas-Henderson-Paradise, NV      asian_cb  0.019246   
74                  New Brunswick-Lakewood, NJ      asian_cb  0.020274   

      odds_ratio variable_check  
2329    1.153441              4  
39      1.175773              4  
353     1.207980              4  
5309    1.217433              4  
74      1.238206              4

#### Largest disparities overall

In [47]:
results_df5[(results_df5['variable_check'] == '5')][['metro_name', 'variable_name', 'p_value', 'odds_ratio', 
                                                     'variable_check']].sort_values(by = ['odds_ratio'],
                                                                                   ascending = False).head(5)

metro_name variable_name   p_value  \
12408                                Waco, TX        latino  0.003080   
18922      Fayetteville-Springdale-Rogers, AR         black  0.007222   
4240                       Port St. Lucie, FL      asian_cb  0.000520   
9397   Rockingham County-Strafford County, NH      asian_cb  0.000215   
11143                    Dayton-Kettering, OH         black  0.000306   

       odds_ratio variable_check  
12408    3.291675              5  
18922    3.098998              5  
4240     3.086573              5  
9397     2.962371              5  
11143    2.882675              5

### 12. Breakdown of metros with disparities
#### Looking at 10 most populous metros

In [50]:
top10_metros = metros_df2.sort_values(by = ['metro_pop'], ascending = False).head(10)
top10_metros

metro_code                                    metro_name  \
621      35614      New York-Jersey City-White Plains, NY-NJ   
508      31084           Los Angeles-Long Beach-Glendale, CA   
166      16984               Chicago-Naperville-Evanston, IL   
396      26420          Houston-The Woodlands-Sugar Land, TX   
48       12060          Atlanta-Sandy Springs-Alpharetta, GA   
215      19124                       Dallas-Plano-Irving, TX   
914      47894  Washington-Arlington-Alexandria, DC-VA-MD-WV   
680      38060                     Phoenix-Mesa-Chandler, AZ   
730      40140          Riverside-San Bernardino-Ontario, CA   
567      33460       Minneapolis-St. Paul-Bloomington, MN-WI   

                        metro_type   metro_pop  
621          Metropolitan Division  11915488.0  
508          Metropolitan Division  10081570.0  
166          Metropolitan Division   7175030.0  
396  Metropolitan Statistical Area   6884138.0  
48   Metropolitan Statistical Area   5862424.0  
215          Metropolitan Division   4903580.0  
914          Metropolitan Division   4901633.0  
680  Metropolitan Statistical Area   4761603.0  
730  Metropolitan Statistical Area   4560470.0  
567  Metropolitan Statistical Area   3573609.0

#### Of the largest metros, Chicago has the worst disparity for Black applicants. Lenders are 2.5 times more likely to deny Black applicants than similarly qualified White applicants. 

In [51]:
results_df5[(results_df5['metro_code'].isin(top10_metros['metro_code'])) & \
            (results_df5['variable_check'] == '5')]\
[['metro_code', 'metro_name', 'metro_pop', 'psuedo_rsquare', 'variable_name', 'p_value', 'odds_ratio']].\
sort_values(by = ['metro_pop', 'odds_ratio'], ascending = False)

metro_code                                    metro_name   metro_pop  \
36        35614      New York-Jersey City-White Plains, NY-NJ  11915488.0   
2328      31084           Los Angeles-Long Beach-Glendale, CA  10081570.0   
2467      16984               Chicago-Naperville-Evanston, IL   7175030.0   
2468      16984               Chicago-Naperville-Evanston, IL   7175030.0   
2119      26420          Houston-The Woodlands-Sugar Land, TX   6884138.0   
3060      12060          Atlanta-Sandy Springs-Alpharetta, GA   5862424.0   
2014      19124                       Dallas-Plano-Irving, TX   4903580.0   
2017      19124                       Dallas-Plano-Irving, TX   4903580.0   
385       47894  Washington-Arlington-Alexandria, DC-VA-MD-WV   4901633.0   
388       47894  Washington-Arlington-Alexandria, DC-VA-MD-WV   4901633.0   
386       47894  Washington-Arlington-Alexandria, DC-VA-MD-WV   4901633.0   
4028      38060                     Phoenix-Mesa-Chandler, AZ   4761603.0   
2850      40140          Riverside-San Bernardino-Ontario, CA   4560470.0   
3475      33460       Minneapolis-St. Paul-Bloomington, MN-WI   3573609.0   
3477      33460       Minneapolis-St. Paul-Bloomington, MN-WI   3573609.0   
3478      33460       Minneapolis-St. Paul-Bloomington, MN-WI   3573609.0   
3476      33460       Minneapolis-St. Paul-Bloomington, MN-WI   3573609.0   

      psuedo_rsquare variable_name       p_value  odds_ratio  
36          0.212318         black  1.540452e-10    1.580497  
2328        0.211224         black  4.564155e-09    1.755397  
2467        0.225103         black  8.646620e-37    2.483044  
2468        0.225103        latino  1.587004e-16    1.591326  
2119        0.224035         black  5.975492e-28    2.041829  
3060        0.247692         black  1.329923e-25    1.729919  
2014        0.273443         black  2.003999e-19    2.101777  
2017        0.273443      asian_cb  1.972840e-16    1.729214  
385         0.249535         black  1.402257e-19    2.073654  
388         0.249535      asian_cb  2.640166e-23    2.028950  
386         0.249535        latino  2.569957e-10    1.709092  
4028        0.202911         black  4.720054e-10    1.890507  
2850        0.210756         black  2.474990e-05    1.628171  
3475        0.266631         black  8.538529e-11    2.154326  
3477        0.266631        native  3.944893e-02    2.067026  
3478        0.266631      asian_cb  2.307718e-08    1.749404  
3476        0.266631        latino  6.427513e-03    1.469225

#### Minneapolis is the only metro where all four race and ethnicites are more likely to be denied. 

In [52]:
results_df5[(results_df5['variable_check'] == '5')]['metro_name'].value_counts(dropna = False).head(5)

Minneapolis-St. Paul-Bloomington, MN-WI    4
Birmingham-Hoover, AL                      3
Indianapolis-Carmel-Anderson, IN           3
Cincinnati, OH-KY-IN                       3
Durham-Chapel Hill, NC                     3
Name: metro_name, dtype: int64

#### Key Metros
#### Chicago Results

In [53]:
results_df5[(results_df5['metro_code'] == '16984')][['metro_code', 'metro_name', 'metro_pop', 'metro_apps',
            'psuedo_rsquare', 'variable_name', 'p_value', 'odds_ratio']]

metro_code                       metro_name  metro_pop  metro_apps  \
2467      16984  Chicago-Naperville-Evanston, IL  7175030.0       57155   
2468      16984  Chicago-Naperville-Evanston, IL  7175030.0       57155   
2469      16984  Chicago-Naperville-Evanston, IL  7175030.0       57155   
2470      16984  Chicago-Naperville-Evanston, IL  7175030.0       57155   

      psuedo_rsquare variable_name       p_value  odds_ratio  
2467        0.225103         black  8.646620e-37    2.483044  
2468        0.225103        latino  1.587004e-16    1.591326  
2469        0.225103        native  3.414332e-01    1.547534  
2470        0.225103      asian_cb  2.562963e-07    1.388372

#### Minneapolis Results

In [55]:
results_df5[(results_df5['metro_code'] == '33460') & ((results_df5['variable_check'] == '4') |\
            (results_df5['variable_check'] == '5'))][['metro_code', 'metro_name', 'metro_pop', 'metro_apps',
            'psuedo_rsquare', 'variable_name', 'p_value', 'odds_ratio']]

metro_code                               metro_name  metro_pop  \
3475      33460  Minneapolis-St. Paul-Bloomington, MN-WI  3573609.0   
3476      33460  Minneapolis-St. Paul-Bloomington, MN-WI  3573609.0   
3477      33460  Minneapolis-St. Paul-Bloomington, MN-WI  3573609.0   
3478      33460  Minneapolis-St. Paul-Bloomington, MN-WI  3573609.0   

      metro_apps  psuedo_rsquare variable_name       p_value  odds_ratio  
3475       42162        0.266631         black  8.538529e-11    2.154326  
3476       42162        0.266631        latino  6.427513e-03    1.469225  
3477       42162        0.266631        native  3.944893e-02    2.067026  
3478       42162        0.266631      asian_cb  2.307718e-08    1.749404

#### Charolette Results

In [56]:
results_df5[(results_df5['metro_code'] == '16740') & ((results_df5['variable_check'] == '4') |\
            (results_df5['variable_check'] == '5'))][['metro_code', 'metro_name', 'metro_pop', 
            'psuedo_rsquare', 'variable_name', 'p_value', 'odds_ratio']]

metro_code                         metro_name  metro_pop  psuedo_rsquare  \
1736      16740  Charlotte-Concord-Gastonia, NC-SC  2545560.0        0.243282   
1737      16740  Charlotte-Concord-Gastonia, NC-SC  2545560.0        0.243282   
1739      16740  Charlotte-Concord-Gastonia, NC-SC  2545560.0        0.243282   

     variable_name       p_value  odds_ratio  
1736         black  1.752335e-06    1.543780  
1737        latino  4.598104e-03    1.307147  
1739      asian_cb  1.757505e-07    1.744474

#### Largest disparites for Latinos

In [57]:
results_df5[(results_df5['variable_check'] == '5') & (results_df5['variable_name'] == 'latino')]\
[['metro_code', 'metro_name', 'metro_pop', 'psuedo_rsquare', 'variable_name', 'p_value', 'odds_ratio']].\
sort_values(by = ['odds_ratio'], ascending = False).head(5)

metro_code                 metro_name  metro_pop  psuedo_rsquare  \
12408      47380                   Waco, TX   268361.0        0.354818   
1841       24660  Greensboro-High Point, NC   762063.0        0.248711   
2259       40060               Richmond, VA  1269530.0        0.262993   
10321      31540                Madison, WI   653725.0        0.248577   
4447       13820      Birmingham-Hoover, AL  1085330.0        0.245919   

      variable_name   p_value  odds_ratio  
12408        latino  0.003080    3.291675  
1841         latino  0.000003    2.740411  
2259         latino  0.000006    2.676193  
10321        latino  0.000884    2.576313  
4447         latino  0.000088    2.411361

#### Largest disparites for AAPI

In [58]:
results_df5[(results_df5['variable_check'] == '5') & (results_df5['variable_name'] == 'asian_cb')]\
[['metro_code', 'metro_name', 'metro_pop', 'psuedo_rsquare', 'variable_name', 'p_value', 'odds_ratio']].\
sort_values(by = ['odds_ratio'], ascending = False).head(5)

metro_code                              metro_name  metro_pop  \
4240       38940                      Port St. Lucie, FL   472012.0   
9397       40484  Rockingham County-Strafford County, NH   435483.0   
2261       40060                            Richmond, VA  1269530.0   
18925      22220      Fayetteville-Springdale-Rogers, AR   514259.0   
2052       41700           San Antonio-New Braunfels, TX  2468193.0   

       psuedo_rsquare variable_name       p_value  odds_ratio  
4240         0.258088      asian_cb  5.200978e-04    3.086573  
9397         0.209597      asian_cb  2.149115e-04    2.962371  
2261         0.262993      asian_cb  2.973412e-07    2.673358  
18925        0.230162      asian_cb  3.072155e-04    2.655565  
2052         0.247725      asian_cb  1.727325e-12    2.560846

#### Largest disparites for Native American applicants

In [59]:
results_df5[(results_df5['variable_check'] == '5') & (results_df5['variable_name'] == 'native')]\
[['metro_code', 'metro_name', 'metro_pop', 'psuedo_rsquare', 'variable_name', 'p_value', 'odds_ratio']].\
sort_values(by = ['odds_ratio'], ascending = False).head(5)

metro_code                               metro_name  metro_pop  \
3477      33460  Minneapolis-St. Paul-Bloomington, MN-WI  3573609.0   

      psuedo_rsquare variable_name   p_value  odds_ratio  
3477        0.266631        native  0.039449    2.067026

#### Largest disparites for Black applicants

In [60]:
results_df5[(results_df5['variable_check'] == '5') & (results_df5['variable_name'] == 'black')]\
[['metro_code', 'metro_name', 'metro_pop', 'psuedo_rsquare', 'variable_name', 'p_value', 'odds_ratio']].\
sort_values(by = ['odds_ratio'], ascending = False).head(5)

metro_code                          metro_name  metro_pop  \
18922      22220  Fayetteville-Springdale-Rogers, AR   514259.0   
11143      19430                Dayton-Kettering, OH   803543.0   
5100       36420                   Oklahoma City, OK  1382841.0   
2258       40060                        Richmond, VA  1269530.0   
5169       44700                        Stockton, CA   742603.0   

       psuedo_rsquare variable_name       p_value  odds_ratio  
18922        0.230162         black  7.221820e-03    3.098998  
11143        0.279138         black  3.058314e-04    2.882675  
5100         0.270741         black  2.024550e-06    2.840909  
2258         0.262993         black  5.007157e-08    2.720363  
5169         0.196393         black  1.838385e-04    2.621905

#### Largest disparites for Native American applicants

In [62]:
results_df5[(results_df5['variable_check'] == '5') & (results_df5['variable_name'] == 'native')]\
[['metro_code', 'metro_name', 'metro_pop', 'psuedo_rsquare', 'variable_name', 'p_value', 'odds_ratio']].\
sort_values(by = ['odds_ratio'], ascending = False).head(5)

metro_code                               metro_name  metro_pop  \
3477      33460  Minneapolis-St. Paul-Bloomington, MN-WI  3573609.0   

      psuedo_rsquare variable_name   p_value  odds_ratio  
3477        0.266631        native  0.039449    2.067026

#### Summary of findings by race and ethnicity
- Black applciants are more likely to be denied in 71 metros
- Latinos in 39 metros
- Asian/Pacific Islander in 55
- Native American in 1 metro

In [63]:
metro_race_bd = pd.pivot_table(results_df5, index = ['variable_name'], columns = ['variable_check'], 
                               values = ['metro_name'], aggfunc = 'count', fill_value = 0).reset_index()

metro_race_bd.columns = metro_race_bd.columns.droplevel(0)
metro_race_bd.columns.name = None
metro_race_bd.columns = ['Race/Ethnicity', 'Missing', 'Not Sig', 'More Apps', 'Small Disparity', 'Disparity']

metro_race_bd

Race/Ethnicity  Missing  Not Sig  More Apps  Small Disparity  Disparity
0       asian_cb        0       61          2               10         55
1          black        1       48          6                2         71
2         latino        0       76          2               11         39
3         native        2      110         15                0          1

### 12. Write out results
#### Add definitions for output

In [64]:
lookup_dict = {'results_flag': ['1', '2', '3', '3', '3', '3', '3'],
               'variable_check': [np.nan, np.nan, '1', '2', '3', '4', '5'],
               'reliable_note': ['No results', 'Not enough variance in variables', 
                                 'Not statistically significant', 'Not statistically significant', 
                                 'Not enough applications', 'Doesn\'t meet level of disparity',
                                 'Statistically significant disparity']}

lookup_df = pd.DataFrame(data=lookup_dict)

lookup_df

results_flag variable_check                        reliable_note
0            1            NaN                           No results
1            2            NaN     Not enough variance in variables
2            3              1        Not statistically significant
3            3              2        Not statistically significant
4            3              3              Not enough applications
5            3              4      Doesn't meet level of disparity
6            3              5  Statistically significant disparity

In [66]:
results_df6 = pd.merge(results_df4, lookup_df, how = 'left', on = ['results_flag', 'variable_check'])

results_df6.loc[(results_df6['variable_check'] == '4') | (results_df6['variable_check'] == '5'),
                'is_reliable'] = True

results_df6.loc[(results_df6['variable_check'] != '4') & (results_df6['variable_check'] != '5'),
                'is_reliable'] = False

results_df6['odds_ratio_rd'] = results_df6['odds_ratio'].round(1)

#### Clean results for all metros:

In [67]:
races_replace = {'black': 'Black', 'latino': 'Latino', 'native': 'Native American', 'asian_cb': 'AAPI'}

results_df7 = results_df6[(results_df6['variable_name'].isin(races))]\
[['metro_code', 'metro_name', 'metro_pop', 'metro_apps', 'metro_type', 'variable_name', 'total_count', 'loan', 
  'denied', 'is_reliable', 'reliable_note', 'odds_ratio_rd']].rename(columns = {'odds_ratio_rd': 'odds_ratio'})

results_df8 = results_df7.replace(races_replace)

results_df8.sample(5, random_state = 303)

metro_code                          metro_name  metro_pop  metro_apps  \
2780       36084      Oakland-Berkeley-Livermore, CA  2799005.0       22676   
30952      17380                       Cleveland, MS    31848.0          75   
18924      22220  Fayetteville-Springdale-Rogers, AR   514259.0        5443   
26016      13780                      Binghamton, NY   241874.0        1070   
29081      24820                      Greenville, OH    51513.0         159   

                          metro_type    variable_name  total_count   loan  \
2780           Metropolitan Division            Black        655.0  591.0   
30952  Micropolitan Statistical Area            Black         10.0    8.0   
18924  Metropolitan Statistical Area  Native American         49.0   46.0   
26016  Metropolitan Statistical Area           Latino         23.0   23.0   
29081  Micropolitan Statistical Area            Black          1.0    1.0   

       denied  is_reliable                        reliable_note  odds_ratio  
2780     64.0         True  Statistically significant disparity         1.7  
30952     2.0        False                           No results         NaN  
18924     3.0        False        Not statistically significant         1.5  
26016     0.0        False                           No results         NaN  
29081     0.0        False                           No results         NaN

In [71]:
results_df8.to_csv('../../findings/metro_findings/1_metro_findings_200823.csv', index = False)